/**
 * §9.6 — AUTO-GENERATED marker helper.
 *
 * Lightweight composer that prepends the canonical marker block to a
 * codegen output file before writing it to `src/`. The deterministic
 * slot/layout grammar from §8.4 is a separate, larger effort tracked
 * by `BLUEPRINT--CODEGEN-MICROTASK-RUNNER`; this helper covers the
 * common case where the runner already produced a single string per
 * target file and the only post-process step needed is the marker.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'

import type { PROTO_AUTO_GENERATED_MARKER } from './marker-constants.js'

export interface ComposeInput {
  /** Absolute path that will receive the file. */
  outputPath: string
  /** SLM-emitted source (already cleaned by `post-process.ts`). */
  body: string
  /** Manifest the body was generated from. Pulled into the marker. */
  manifestPath: string
  /** Feature id (`FEAT--...`). Pulled into the regenerate hint. */
  feature: string
  /** Optional comment prefix override. Default `// ` (works for TS/JS/CSS). */
  commentPrefix?: string
}

const DEFAULT_PREFIX = '// '

/** The marker the validator (PROTO--AUTO-GENERATED-MARKER) looks for. */
export const AUTO_GENERATED_MARKER_TAG = 'AUTO-GENERATED — DO NOT EDIT'

export function buildAutoGeneratedMarker(input: ComposeInput): string {
  const p = input.commentPrefix ?? DEFAULT_PREFIX
  return [
    `${p}${AUTO_GENERATED_MARKER_TAG}`,
    `${p}Source: ${input.manifestPath}`,
    `${p}Regenerate: npm run msp:run-task ${input.feature}`,
    '',
  ].join('\n')
}

export async function composeWithMarker(input: ComposeInput): Promise<void> {
  await mkdir(dirname(input.outputPath), { recursive: true })
  const header = buildAutoGeneratedMarker(input)
  await writeFile(input.outputPath, header + input.body, 'utf8')
}

export function bodyContainsMarker(body: string): boolean {
  return body.includes(AUTO_GENERATED_MARKER_TAG)
}
