/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OpenOptions {
  path: string
  pageCacheMb?: number
  readOnly?: boolean
}
export interface NodeInput {
  id?: string
  labels: Array<string>
  props?: any
}
export interface NodeOutput {
  id: string
  labels: Array<string>
  props: any
}
export interface EdgeInput {
  id?: string
  from: string
  to: string
  rel: string
  props?: any
  validFrom?: string
  supersede?: boolean
}
export interface EdgeOutput {
  id: string
  from: string
  to: string
  rel: string
  props: any
  validFrom: string
  validTo?: string
  recordedAt: string
  supersededBy?: string
}
export interface QueryInput {
  from?: string
  to?: string
  rel?: string
  asOf?: string
  includeInvalid?: boolean
  limit?: number
}
export interface NeighborInput {
  depth?: number
  rel?: string
  direction?: string
  asOf?: string
  includeInvalid?: boolean
  limit?: number
}
export interface NeighborOutput {
  node: NodeOutput
  path: Array<EdgeOutput>
  depth: number
}
export interface DatabaseStatus {
  open: boolean
  readOnly: boolean
  pageCacheMb: number
}
export declare function engineNameSync(): string
export declare class GenesisDatabase {
  static open(opts: OpenOptions): GenesisDatabase
  addNode(args: NodeInput): Promise<NodeOutput>
  addEdge(args: EdgeInput): Promise<EdgeOutput>
  retractEdge(id: string, at?: string | undefined | null): Promise<EdgeOutput | null>
  query(args: QueryInput): Promise<Array<EdgeOutput>>
  neighbors(seed: string, args: NeighborInput): Promise<Array<NeighborOutput>>
  cypher(query: string): Promise<any>
  schemaVersionSync(): number
  statusSync(): DatabaseStatus
}
