import { describe, expect, it } from 'vitest'
import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  AUTO_GENERATED_MARKER_TAG,
  bodyContainsMarker,
  buildAutoGeneratedMarker,
  composeWithMarker,
} from '../../src/cognitive/compose.js'

describe('compose — AUTO-GENERATED marker (§9.6)', () => {
  it('builds the canonical 3-line header', () => {
    const out = buildAutoGeneratedMarker({
      outputPath: '/tmp/foo.ts',
      body: '',
      manifestPath: '.brain/tasks/FEAT--X/manifest.yaml',
      feature: 'FEAT--X',
    })
    expect(out).toContain(AUTO_GENERATED_MARKER_TAG)
    expect(out).toContain('Source: .brain/tasks/FEAT--X/manifest.yaml')
    expect(out).toContain('Regenerate: npm run msp:run-task FEAT--X')
  })

  it('composeWithMarker writes the marker + body to disk', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'compose-marker-'))
    const path = join(dir, 'subdir', 'output.ts')
    await composeWithMarker({
      outputPath: path,
      body: 'export const x = 1\n',
      manifestPath: '.brain/tasks/FEAT--X/manifest.yaml',
      feature: 'FEAT--X',
    })
    const written = await readFile(path, 'utf8')
    expect(bodyContainsMarker(written)).toBe(true)
    expect(written).toContain('export const x = 1')
  })

  it('respects a custom commentPrefix (e.g. # for python)', () => {
    const out = buildAutoGeneratedMarker({
      outputPath: '/tmp/x.py',
      body: '',
      manifestPath: 'x.yaml',
      feature: 'FEAT--Y',
      commentPrefix: '# ',
    })
    expect(out.startsWith('# AUTO-GENERATED')).toBe(true)
  })
})
