/*
THIS IS A GENERATED/BUNDLED FILE.
IF YOU WANT TO VIEW THE SOURCE VISIT THE REPOSITORY FOR THIS PLUGIN.
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MSPBridgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/server.ts
var http = __toESM(require("http"));
var BridgeServer = class {
  constructor(app) {
    this.app = app;
    this.server = null;
  }
  start(opts) {
    this.server = http.createServer(async (req, res) => {
      res.setHeader("Access-Control-Allow-Origin", "*");
      res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
      res.setHeader("Access-Control-Allow-Headers", "Content-Type");
      if (req.method === "OPTIONS") {
        res.writeHead(204);
        res.end();
        return;
      }
      if (req.url === "/api/semantic-search" && req.method === "POST") {
        let body = "";
        req.on("data", (chunk) => {
          body += chunk.toString();
        });
        req.on("end", async () => {
          try {
            const data = JSON.parse(body);
            const query = data.query;
            const limit = data.limit || 10;
            if (!query) {
              res.writeHead(400, { "Content-Type": "application/json" });
              res.end(JSON.stringify({ error: "Missing query parameter" }));
              return;
            }
            const mockHits = [
              { id: "CONCEPT--MSP-BRIDGE-PLUGIN", score: 0.95, text: "This is a mock hit." }
            ];
            res.writeHead(200, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ hits: mockHits }));
          } catch (err) {
            res.writeHead(500, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: err.message }));
          }
        });
      } else {
        res.writeHead(404, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Not Found" }));
      }
    });
    this.server.listen(opts.port, () => {
      console.log(`msp-bridge server listening on port ${opts.port}`);
    });
  }
  stop() {
    if (this.server) {
      this.server.close();
      console.log("msp-bridge server stopped");
    }
  }
};

// src/sync.ts
var import_obsidian = require("obsidian");
var BridgeSync = class {
  constructor(app) {
    this.app = app;
  }
  initialize() {
    this.app.vault.on("modify", (file) => this.handleFileChange(file, "modify"));
    this.app.vault.on("create", (file) => this.handleFileChange(file, "create"));
    this.app.vault.on("delete", (file) => this.handleFileChange(file, "delete"));
    this.app.vault.on("rename", (file, oldPath) => this.handleFileRename(file, oldPath));
    console.log("msp-bridge synchronization initialized");
  }
  async handleFileChange(file, type) {
    if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") return;
    console.log(`msp-bridge: detected ${type} on ${file.path}`);
    if (type === "delete") {
      return;
    }
  }
  handleFileRename(file, oldPath) {
    if (!(file instanceof import_obsidian.TFile) || file.extension !== "md") return;
    console.log(`msp-bridge: detected rename from ${oldPath} to ${file.path}`);
  }
};

// src/main.ts
var MSPBridgePlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.server = null;
    this.sync = null;
  }
  async onload() {
    console.log("loading msp-bridge plugin");
    this.server = new BridgeServer(this.app);
    this.server.start({ port: 3e3 });
    this.sync = new BridgeSync(this.app);
    this.sync.initialize();
  }
  onunload() {
    console.log("unloading msp-bridge plugin");
    if (this.server) {
      this.server.stop();
    }
  }
};
